apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-apache-deployment
  labels:
    app: apache-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache-app
  template:
    metadata:
      labels:
        app: apache-app
    spec:
      containers:
      - name: capestonenginx
        image: annantguptacs15/capestonenginx:latest
        ports:
        - containerPort: 80